#	Для корректной работы с кириллицей используется пакет libncursesw5-dev
fileManager: main.c getDirPath.c fm_print.c fm_list.c getDirPath.h fm_window.h fm_print.h fm_list.h properties.h
				gcc main.c getDirPath.c fm_print.c fm_list.c -o fileManager -l ncursesw -g
