tree1: tree1.c
				gcc tree1.c -o tree1

tree2: tree2.c
				gcc tree2.c -o tree2

tree3: tree3.c
				gcc tree3.c -o tree3

tree4: tree4.c
				gcc tree4.c -o tree4

tree5: tree5.c
				gcc tree5.c -o tree5

tree6: tree6.c
				gcc tree6.c -o tree6
