tree: tree1.c tree2.c tree3.c tree4.c tree5.c tree6.c
				gcc tree1.c -o tree1
				gcc tree2.c -o tree2
				gcc tree3.c -o tree3
				gcc tree4.c -o tree4
				gcc tree5.c -o tree5
				gcc tree6.c -o tree6
