interpreter: main.c input.c parser.c moveDataAndErase.c execute_p.c input.h parser.h moveDataAndErase.h execute_p.h
				gcc main.c input.c parser.c moveDataAndErase.c execute_p.c -o interpreter -g

clear:
				rm tmp1
				rm tmp2
